/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Информация о чате
 */
export interface ChatDTO { 
    /**
     * Идентификатор чата
     */
    id: number;
    /**
     * Название чата
     */
    name: string;
    /**
     * Описание чата
     */
    description: string;
    /**
     * Создатель чата
     */
    creatorId: number;
    /**
     * Тип чата
     */
    type: ChatDTO.TypeEnum;
    /**
     * Дата и время создания чата
     */
    createdAt: string;
}
export namespace ChatDTO {
    export type TypeEnum = 'PRIVATE' | 'GROUP' | 'SELF';
    export const TypeEnum = {
        Private: 'PRIVATE' as TypeEnum,
        Group: 'GROUP' as TypeEnum,
        Self: 'SELF' as TypeEnum
    };
}


