/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Запрос для создания нового чата
 */
export interface ChatCreateRequest { 
    /**
     * Список идентификаторов пользователей для чата. Все ID должны быть положительными.
     */
    userIds?: Array<number>;
    /**
     * Тип чата, который будет создан.
     */
    chatType: ChatCreateRequest.ChatTypeEnum;
}
export namespace ChatCreateRequest {
    export type ChatTypeEnum = 'PRIVATE' | 'GROUP' | 'SELF';
    export const ChatTypeEnum = {
        Private: 'PRIVATE' as ChatTypeEnum,
        Group: 'GROUP' as ChatTypeEnum,
        Self: 'SELF' as ChatTypeEnum
    };
}


