/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Ответ при добавлении пользователя в чат
 */
export interface ChatUserCreateResponse { 
    /**
     * Идентификатор чата
     */
    chatId: number;
    /**
     * Идентификатор пользователя
     */
    userId: number;
    /**
     * Дата и время присоединения пользователя к чату
     */
    joinedAt: string;
}

