/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Информация о чате
 */
export interface ChatDTO { 
    /**
     * Идентификатор чата
     */
    id: number;
    /**
     * Название чата
     */
    name: string;
    /**
     * Описание чата
     */
    description: string;
    /**
     * Дата и время создания чата
     */
    createdAt: string;
}

