/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Ответ при удалении пользователей из чата
 */
export interface ChatUserDeleteResponse { 
    /**
     * Идентификатор чата
     */
    chatId: number;
    /**
     * Список выгнанных идентификаторов пользователей из чата.
     */
    userIds?: Array<number>;
}

