/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Ответ c токеном доступа
 */
export interface LoginResponse { 
    /**
     * Токен доступа
     */
    accessToken: string;
    /**
     * Рефреш токен
     */
    refreshToken: string;
}

