/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Представление сообщения в чате, включая ID, чат, отправителя, текст и время отправки
 */
export interface MessageDTO { 
    /**
     * Идентификатор сообщения
     */
    id: number;
    /**
     * Идентификатор чата, в котором находится сообщение
     */
    chatId: number;
    /**
     * Идентификатор отправителя сообщения
     */
    senderId: number;
    /**
     * Текст сообщения
     */
    content: string;
    /**
     * Дата и время отправки сообщения
     */
    sentAt: string;
}

