/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Запрос на обновление содержания сообщения
 */
export interface MessageUpdateRequest { 
    /**
     * Новый текст сообщения
     */
    content?: string;
}

